---
- hosts: all

  become: true
  tasks:
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes
        
    - name: Install Qemu-Guest-Agent
      ansible.builtin.apt:
        name:
          - qemu-guest-agent
        state: present
