---
- hosts: k8s_cluster
  become: true
  tasks:
    - name: Test Reacheability
      ansible.builtin.ping:

    - name: Update Cache
      ansible.builtin.apt:
        update_cache: true
        autoclean: true

    - name: Upgrade All the Packages to the latest
      ansible.builtin.apt:
        upgrade: "full"

    - name: Install Qemu-Guest-Agent
      ansible.builtin.apt:
        name:
          - qemu-guest-agent
        state: present

    - name: Set the timezone
      ansible.builtin.timezone:
        name: Asia/Manila

    - name: Reboot
      ansible.builtin.reboot:
      register: system_reboot

    - name: Verify Reboot Success
      ansible.builtin.ping:
      when: system_reboot.rebooted

    - name: Update Cache
      ansible.builtin.apt:
        update_cache: true
        autoclean: true
